// Mocks generated by Mockito 5.4.6 from annotations
// in reeder/test/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:connectivity_plus/connectivity_plus.dart' as _i13;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i14;
import 'package:flutter/foundation.dart' as _i12;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:reeder/core/database/app_database.dart' as _i8;
import 'package:reeder/data/datasources/local/sync_local_ds.dart' as _i6;
import 'package:reeder/data/services/auth/auth_service.dart' as _i11;
import 'package:reeder/data/services/sync/sync_models.dart' as _i2;
import 'package:reeder/data/services/sync/sync_queue.dart' as _i9;
import 'package:reeder/data/services/sync/sync_service.dart' as _i5;
import 'package:reeder/data/services/sync/sync_service_registry.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncFeed_0 extends _i1.SmartFake implements _i2.SyncFeed {
  _FakeSyncFeed_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncFolder_1 extends _i1.SmartFake implements _i2.SyncFolder {
  _FakeSyncFolder_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_2 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSOptions_3 extends _i1.SmartFake implements _i3.IOSOptions {
  _FakeIOSOptions_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_4 extends _i1.SmartFake
    implements _i3.AndroidOptions {
  _FakeAndroidOptions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_5 extends _i1.SmartFake implements _i3.LinuxOptions {
  _FakeLinuxOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_6 extends _i1.SmartFake
    implements _i3.WindowsOptions {
  _FakeWindowsOptions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_7 extends _i1.SmartFake implements _i3.WebOptions {
  _FakeWebOptions_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMacOsOptions_8 extends _i1.SmartFake implements _i3.MacOsOptions {
  _FakeMacOsOptions_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncServiceRegistry].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncServiceRegistry extends _i1.Mock
    implements _i4.SyncServiceRegistry {
  MockSyncServiceRegistry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.SyncServiceType> get registeredTypes => (super.noSuchMethod(
        Invocation.getter(#registeredTypes),
        returnValue: <_i2.SyncServiceType>[],
      ) as List<_i2.SyncServiceType>);

  @override
  List<_i4.SyncServiceInfo> get availableServices => (super.noSuchMethod(
        Invocation.getter(#availableServices),
        returnValue: <_i4.SyncServiceInfo>[],
      ) as List<_i4.SyncServiceInfo>);

  @override
  void registerFactory(
    _i2.SyncServiceType? type,
    _i5.SyncService Function()? factory,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #registerFactory,
          [
            type,
            factory,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void register(_i5.SyncService? service) => super.noSuchMethod(
        Invocation.method(
          #register,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.SyncService? getService(_i2.SyncServiceType? type) =>
      (super.noSuchMethod(Invocation.method(
        #getService,
        [type],
      )) as _i5.SyncService?);

  @override
  bool setActiveService(_i2.SyncServiceType? type) => (super.noSuchMethod(
        Invocation.method(
          #setActiveService,
          [type],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearActiveService() => super.noSuchMethod(
        Invocation.method(
          #clearActiveService,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SyncLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncLocalDataSource extends _i1.Mock
    implements _i6.SyncLocalDataSource {
  MockSyncLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<int> upsertAccount(_i8.SyncAccountsCompanion? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertAccount,
          [account],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<_i8.SyncAccount?> getAccountById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getAccountById,
          [id],
        ),
        returnValue: _i7.Future<_i8.SyncAccount?>.value(),
      ) as _i7.Future<_i8.SyncAccount?>);

  @override
  _i7.Future<List<_i8.SyncAccount>> getAllAccounts() => (super.noSuchMethod(
        Invocation.method(
          #getAllAccounts,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.SyncAccount>>.value(<_i8.SyncAccount>[]),
      ) as _i7.Future<List<_i8.SyncAccount>>);

  @override
  _i7.Future<_i8.SyncAccount?> getActiveAccount() => (super.noSuchMethod(
        Invocation.method(
          #getActiveAccount,
          [],
        ),
        returnValue: _i7.Future<_i8.SyncAccount?>.value(),
      ) as _i7.Future<_i8.SyncAccount?>);

  @override
  _i7.Future<void> setActiveAccount(int? accountId) => (super.noSuchMethod(
        Invocation.method(
          #setActiveAccount,
          [accountId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> deleteAccount(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [id],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<int> enqueueAction(_i8.SyncQueueItemsCompanion? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueAction,
          [item],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<_i8.SyncQueueItem?> dequeueAction(int? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #dequeueAction,
          [accountId],
        ),
        returnValue: _i7.Future<_i8.SyncQueueItem?>.value(),
      ) as _i7.Future<_i8.SyncQueueItem?>);

  @override
  _i7.Future<List<_i8.SyncQueueItem>> getAllQueueItems(int? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllQueueItems,
          [accountId],
        ),
        returnValue:
            _i7.Future<List<_i8.SyncQueueItem>>.value(<_i8.SyncQueueItem>[]),
      ) as _i7.Future<List<_i8.SyncQueueItem>>);

  @override
  _i7.Future<int> deleteQueueItemsByAccountId(int? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteQueueItemsByAccountId,
          [accountId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> incrementRetryCount(int? queueItemId) => (super.noSuchMethod(
        Invocation.method(
          #incrementRetryCount,
          [queueItemId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> deleteQueueItem(int? queueItemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteQueueItem,
          [queueItemId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<int> upsertMapping(_i8.RemoteIdMappingsCompanion? mapping) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMapping,
          [mapping],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<String?> getRemoteId(
    int? accountId,
    String? localType,
    int? localId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemoteId,
          [
            accountId,
            localType,
            localId,
          ],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<int?> getLocalId(
    int? accountId,
    String? localType,
    String? remoteId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalId,
          [
            accountId,
            localType,
            remoteId,
          ],
        ),
        returnValue: _i7.Future<int?>.value(),
      ) as _i7.Future<int?>);

  @override
  _i7.Future<int> deleteMappingsByAccountId(int? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMappingsByAccountId,
          [accountId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<bool> deleteMapping(int? mappingId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMapping,
          [mappingId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [SyncQueue].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncQueue extends _i1.Mock implements _i9.SyncQueue {
  MockSyncQueue() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> enqueue(
    int? accountId,
    _i9.SyncQueueAction? action,
    List<String>? itemIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueue,
          [
            accountId,
            action,
            itemIds,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> processQueue(
    int? accountId,
    _i5.SyncService? syncService,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processQueue,
          [
            accountId,
            syncService,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> getQueueSize(int? accountId) => (super.noSuchMethod(
        Invocation.method(
          #getQueueSize,
          [accountId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> clearQueue(int? accountId) => (super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [accountId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i5.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SyncServiceType get serviceType => (super.noSuchMethod(
        Invocation.getter(#serviceType),
        returnValue: _i2.SyncServiceType.local,
      ) as _i2.SyncServiceType);

  @override
  String get serviceName => (super.noSuchMethod(
        Invocation.getter(#serviceName),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#serviceName),
        ),
      ) as String);

  @override
  String get serviceIcon => (super.noSuchMethod(
        Invocation.getter(#serviceIcon),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#serviceIcon),
        ),
      ) as String);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<bool> authenticate(_i2.SyncCredentials? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [credentials],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> validateCredentials() => (super.noSuchMethod(
        Invocation.method(
          #validateCredentials,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i2.SyncFeed>> getFeeds() => (super.noSuchMethod(
        Invocation.method(
          #getFeeds,
          [],
        ),
        returnValue: _i7.Future<List<_i2.SyncFeed>>.value(<_i2.SyncFeed>[]),
      ) as _i7.Future<List<_i2.SyncFeed>>);

  @override
  _i7.Future<_i2.SyncFeed> addFeed(
    String? feedUrl, {
    String? title,
    String? folderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFeed,
          [feedUrl],
          {
            #title: title,
            #folderId: folderId,
          },
        ),
        returnValue: _i7.Future<_i2.SyncFeed>.value(_FakeSyncFeed_0(
          this,
          Invocation.method(
            #addFeed,
            [feedUrl],
            {
              #title: title,
              #folderId: folderId,
            },
          ),
        )),
      ) as _i7.Future<_i2.SyncFeed>);

  @override
  _i7.Future<void> removeFeed(String? feedRemoteId) => (super.noSuchMethod(
        Invocation.method(
          #removeFeed,
          [feedRemoteId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> renameFeed(
    String? feedRemoteId,
    String? newTitle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFeed,
          [
            feedRemoteId,
            newTitle,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> moveFeed(
    String? feedRemoteId,
    String? folderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveFeed,
          [
            feedRemoteId,
            folderId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.SyncFolder>> getFolders() => (super.noSuchMethod(
        Invocation.method(
          #getFolders,
          [],
        ),
        returnValue: _i7.Future<List<_i2.SyncFolder>>.value(<_i2.SyncFolder>[]),
      ) as _i7.Future<List<_i2.SyncFolder>>);

  @override
  _i7.Future<_i2.SyncFolder> createFolder(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [name],
        ),
        returnValue: _i7.Future<_i2.SyncFolder>.value(_FakeSyncFolder_1(
          this,
          Invocation.method(
            #createFolder,
            [name],
          ),
        )),
      ) as _i7.Future<_i2.SyncFolder>);

  @override
  _i7.Future<void> deleteFolder(String? folderRemoteId) => (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [folderRemoteId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> renameFolder(
    String? folderRemoteId,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFolder,
          [
            folderRemoteId,
            newName,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.SyncArticle>> getArticles({
    DateTime? since,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticles,
          [],
          {
            #since: since,
            #limit: limit,
          },
        ),
        returnValue:
            _i7.Future<List<_i2.SyncArticle>>.value(<_i2.SyncArticle>[]),
      ) as _i7.Future<List<_i2.SyncArticle>>);

  @override
  _i7.Future<List<String>> getUnreadArticleIds() => (super.noSuchMethod(
        Invocation.method(
          #getUnreadArticleIds,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<List<String>> getStarredArticleIds() => (super.noSuchMethod(
        Invocation.method(
          #getStarredArticleIds,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<void> markAsRead(List<String>? articleRemoteIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [articleRemoteIds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markAsUnread(List<String>? articleRemoteIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsUnread,
          [articleRemoteIds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markAsStarred(List<String>? articleRemoteIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsStarred,
          [articleRemoteIds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markAsUnstarred(List<String>? articleRemoteIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsUnstarred,
          [articleRemoteIds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markFeedAsRead(String? feedRemoteId) => (super.noSuchMethod(
        Invocation.method(
          #markFeedAsRead,
          [feedRemoteId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.SyncResult> fullSync() => (super.noSuchMethod(
        Invocation.method(
          #fullSync,
          [],
        ),
        returnValue: _i7.Future<_i2.SyncResult>.value(_FakeSyncResult_2(
          this,
          Invocation.method(
            #fullSync,
            [],
          ),
        )),
      ) as _i7.Future<_i2.SyncResult>);

  @override
  _i7.Future<_i2.SyncResult> incrementalSync({DateTime? since}) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementalSync,
          [],
          {#since: since},
        ),
        returnValue: _i7.Future<_i2.SyncResult>.value(_FakeSyncResult_2(
          this,
          Invocation.method(
            #incrementalSync,
            [],
            {#since: since},
          ),
        )),
      ) as _i7.Future<_i2.SyncResult>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i11.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> saveCredentials(
    int? accountId,
    _i2.SyncCredentials? credentials,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCredentials,
          [
            accountId,
            credentials,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.SyncCredentials?> getCredentials(int? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCredentials,
          [accountId],
        ),
        returnValue: _i7.Future<_i2.SyncCredentials?>.value(),
      ) as _i7.Future<_i2.SyncCredentials?>);

  @override
  _i7.Future<void> deleteCredentials(int? accountId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCredentials,
          [accountId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateTokens(
    int? accountId, {
    required String? accessToken,
    String? refreshToken,
    DateTime? tokenExpiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTokens,
          [accountId],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #tokenExpiresAt: tokenExpiresAt,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> hasCredentials(int? accountId) => (super.noSuchMethod(
        Invocation.method(
          #hasCredentials,
          [accountId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> deleteAllCredentials() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllCredentials,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i3.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_3(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i3.IOSOptions);

  @override
  _i3.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_4(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i3.AndroidOptions);

  @override
  _i3.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_5(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i3.LinuxOptions);

  @override
  _i3.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_6(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i3.WindowsOptions);

  @override
  _i3.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_7(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i3.WebOptions);

  @override
  _i3.MacOsOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeMacOsOptions_8(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i3.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i12.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterListener({
    required String? key,
    required _i12.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterAllListenersForKey,
          [],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
        Invocation.method(
          #unregisterAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> write({
    required String? key,
    required String? value,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> read({
    required String? key,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> containsKey({
    required String? key,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> delete({
    required String? key,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, String>> readAll({
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<void> deleteAll({
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool?> isCupertinoProtectedDataAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isCupertinoProtectedDataAvailable,
          [],
        ),
        returnValue: _i7.Future<bool?>.value(),
      ) as _i7.Future<bool?>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i13.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<List<_i14.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i7.Stream<List<_i14.ConnectivityResult>>.empty(),
      ) as _i7.Stream<List<_i14.ConnectivityResult>>);

  @override
  _i7.Future<List<_i14.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i7.Future<List<_i14.ConnectivityResult>>.value(
            <_i14.ConnectivityResult>[]),
      ) as _i7.Future<List<_i14.ConnectivityResult>>);
}
