// Mocks generated by Mockito 5.4.4 from annotations
// in reeder/test/data/services/feed_discovery_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:reeder/core/network/dio_client.dart' as _i4;
import 'package:reeder/data/datasources/remote/rss_remote_ds.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFeedParseResult_2 extends _i1.SmartFake
    implements _i3.FeedParseResult {
  _FakeFeedParseResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i4.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i5.Future<_i2.Response<T>> get<T>(
    String? url, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
          this,
          Invocation.method(
            #get,
            [url],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> post<T>(
    String? url, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<List<int>>> getBytes(
    String? url, {
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBytes,
          [url],
          {#cancelToken: cancelToken},
        ),
        returnValue: _i5.Future<_i2.Response<List<int>>>.value(
            _FakeResponse_1<List<int>>(
          this,
          Invocation.method(
            #getBytes,
            [url],
            {#cancelToken: cancelToken},
          ),
        )),
      ) as _i5.Future<_i2.Response<List<int>>>);

  @override
  _i5.Future<String> getString(
    String? url, {
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getString,
          [url],
          {#cancelToken: cancelToken},
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getString,
            [url],
            {#cancelToken: cancelToken},
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [RssRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRssRemoteDataSource extends _i1.Mock
    implements _i3.RssRemoteDataSource {
  MockRssRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.FeedParseResult> fetchFeed(String? feedUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFeed,
          [feedUrl],
        ),
        returnValue:
            _i5.Future<_i3.FeedParseResult>.value(_FakeFeedParseResult_2(
          this,
          Invocation.method(
            #fetchFeed,
            [feedUrl],
          ),
        )),
      ) as _i5.Future<_i3.FeedParseResult>);
}
